import React from 'react'
import "./AllTours.scss"
import FrontCard from '../components/FrontOnlyCard/FrontCard'
import SearchBar from '../components/SearchBar/SearchBar'
const AllTours = () => {
  

  return (<>

    <SearchBar/>
    <div className='row'>
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--1"
                   headingSpan="card__heading-span--1"
                   backSideNumber = "card__side--back-1"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--2"
                   headingSpan="card__heading-span--2"
                   backSideNumber = "card__side--back-2"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
    </div>
    <div className='row'>
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--1"
                   headingSpan="card__heading-span--1"
                   backSideNumber = "card__side--back-1"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--2"
                   headingSpan="card__heading-span--2"
                   backSideNumber = "card__side--back-2"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
    </div>
    <div className='row'>
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--1"
                   headingSpan="card__heading-span--1"
                   backSideNumber = "card__side--back-1"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--2"
                   headingSpan="card__heading-span--2"
                   backSideNumber = "card__side--back-2"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
    </div>
    <div className='row'>
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--1"
                   headingSpan="card__heading-span--1"
                   backSideNumber = "card__side--back-1"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--2"
                   headingSpan="card__heading-span--2"
                   backSideNumber = "card__side--back-2"
                   />
        <FrontCard title="Snow Adventure"
                   featur1="5 day tours"
                   featur2="Up to 15 people"
                   featur3="3 tour guides"
                   featur4="Sleep in provided tent"
                   featur5= "Difficultsy: Hard"
                   priceMessage="Only"
                   price= "$833"
                   picture= "card__picture--3"
                   headingSpan="card__heading-span--3"
                   backSideNumber = "card__side--back-3"
                   />
    </div>


                   </>
  )
}

export default AllTours